version: "3"

services:

  team_postgres:
    image: postgres:10.4-alpine
    container_name: team_postgres
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/init.sql
      - /tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  team_server:
    container_name: team_server
    build:
      context: .
      dockerfile: devDockerfile
    environment:
      - TEAM_DATABASE_URL=postgres://postgres:@team_postgres:5432/team
      - TEAM_DOMAIN=${TEAM_DOMAIN}
      - TEAM_SLACK=${TEAM_SLACK}
      - TEAM_GOOGLE_CLIENT_ID=${TEAM_GOOGLE_CLIENT_ID}
      - TEAM_GOOGLE_CLIENT_SECRET=${TEAM_GOOGLE_CLIENT_SECRET}
      - TEAM_GOOGLE_REDIRECT_URL=${TEAM_GOOGLE_REDIRECT_URL}
      - TEAM_GOOGLE_ALLOW_DOMAIN=${TEAM_GOOGLE_ALLOW_DOMAIN}
      - TEAM_SECRET_COOKIE=${TEAM_SECRET_COOKIE}
      - RUST_BACKTRACE=${TEAM_RUST_BACKTRACE}
    volumes:
      - .:/source
    logging:
      options:
        max-size: "500k"
    ports:
      - "3000:3000"
    external_links:
      - team_postgres
